### PR TITLE
Closes #44, Task screen CSS now appears in Task popup

### LINKED ISSUE #44: CSS not being applied to Task Scene
**Location**: Task.fxml

**Observed behaviour**: CSS styling is not being applied to the popup scene

**Operating System**: Windows 11

**Steps to reproduce**:

1. Open the Task.fxml scene from the MainScreen.fxml scene. 
2. Observe the lack of CSS style applied to the popup scene

**Potential cause**: This may be because the task.css file is not being applied to the popup window on the startup

**Screenshots**:
image

### PR DESCRIPTION
**Pull request by ochu761**
Closes #44.
Added stylesheets="@MainScreen.css" to Task.fxml root AnchorPane

### CODE REVIEW

**Comment by ochu761** [comment]
Great looking CSS @poli648! Please check if theres any issues compared to how you designed in SceneBuilder. Noticed there was white background behind the rounded borders, but can resolve this in a separate issue (tidying CSS, including file organisation)

Screen Shot 2022-08-22 at 12 51 02 AM

**Comment by jzho987** [comment]
Everything looks good! Another thing to add would be to darken the background if possible.

**Review by ktha423 — APPROVED** [review]
Looks good, see no issues, approving changes

**Review by poli648 — APPROVED** [review]
Such a simple solution! Good work finding it!

**Pull request merged**
